# Habilita repositorios MongoDB con perfil mongo
spring.data.mongodb.repositories.type=auto

# MongoDB activo
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/db_order_manager}
spring.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:db_order_manager}