spring.application.name=order-manager

server.port=${SERVER_PORT:8086}
server.servlet.context-path=${SERVER_SERVLET_CONTEXT_PATH:/order/api/v1}

# ================================
# POSTGRESQL
# ================================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_order_manager}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.open-in-view=false

# ================================
# PERFILES
# ================================
spring.profiles.active=jpa
# spring.profiles.active=mongo

# ================================
# JACKSON
# ================================
spring.jackson.date-format=dd/MM/yyyy HH:mm:ss
spring.jackson.time-zone=America/Bogota

#logging.level.root=INFO
#logging.level.edu.ordermanager=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.pattern.console=%d{dd/MM/yyyy HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
#logging.file.name=logs/order-manager.log
#logging.file.max-size=10MB
#logging.file.max-history=30